### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by jrreich** [alcfeoh/tesla-server#1]
I tried cloning the repo and then importing some of the modules into my javascript code but when I attempt to call getVehicles for instance, I get the same preflight CORS error. 

Do you run this as a node express server or something?  

> Yes, it has to be run as a server with Node. That server acts as a proxy with the Tesla API.
> In other words, what you need to do is:
> 
> 1. Check out the code
> 2. run `npm install` in your project folder
> 3. run `node index.js` to start the server
> 
> Then your Javascript code can make HTTP requests to the endpoints described in `index.js`.
> Note that I haven't kept it updated with the latest additions to the Tesla API. It is possible that some of these endpoints aren't working anymore.

Thanks for the very quick reply... I was typing my reply to myself to say that I should've read the code a bit further before posting an issue. Thanks again.

**Comment by alcfeoh** [comment]
Yes, it has to be run as a server with Node. That server acts as a proxy with the Tesla API.
In other words, what you need to do is:
1) Check out the code
2) run `npm install` in your project folder
3) run `node index.js` to start the server

Then your Javascript code can make HTTP requests to the endpoints described in `index.js`.
Note that I haven't kept it updated with the latest additions to the Tesla API. It is possible that some of these endpoints aren't working anymore.
